# Generated by Django 5.2.15 on 2026-06-23 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='sops.sop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_compliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOP Compliance',
                'verbose_name_plural': 'SOP Compliances',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sop')},
            },
        ),
    ]
